import { Product } from "../types/product";

export const products: Product[] = [
  {
    id: "1",
    name: "Diabetes Care Juice",
    slug: "diabetes-care",
    price: 499,
    image: "/certifiedIcons/product.jpeg",
    category: "diabetes-care",
  },
  {
    id: "2",
    name: "Heart Care Juice",
    slug: "heart-care",
    price: 599,
    image: "/certifiedIcons/product.jpeg",
    category: "heart-care",
  },
  {
    id: "3",
    name: "Hair Care Oil",
    slug: "hair-care",
    price: 399,
    image: "/certifiedIcons/product.jpeg",
    category: "hair-care",
  },
  {
    id: "4",
    name: "Women's Care Product",
    slug: "womens-care",
    price: 499,
    image: "/certifiedIcons/product.jpeg",
    category: "womens-care",
  },
  {
    id: "5",
    name: "Joint Care Product",
    slug: "joint-care",
    price: 499,
    image: "/certifiedIcons/product.jpeg",
    category: "joint-care",
  },
  {
    id: "6",
    name: "Immunity Booster Product",
    slug: "immunity-booster",
    price: 499,
    image: "/certifiedIcons/product.jpeg",
    category: "immunity-booster",
  },
  {
    id: "7",
    name: "Blood Pressure Product",
    slug: "blood-pressure",
    price: 499,
    image: "/certifiedIcons/product.jpeg",
    category: "blood-pressure",
  },
  {
    id: "8",
    name: "Skin Care Product",
    slug: "skin-care",
    price: 499,
    image: "/certifiedIcons/product.jpeg",
    category: "skin-care",
  },
  {
    id: "9",
    name: "Men's Care Product",
    slug: "mens-care",
    price: 499,
    image: "/certifiedIcons/product.jpeg",
    category: "mens-care",
  },
  // featured items that were previously hard‑coded elsewhere
  {
    id: "10",
    name: "Amla Juice",
    slug: "amla-juice",
    price: 299,
    image: "/certifiedIcons/product.jpeg",
    category: "featured",
    rating: 4,
  },
  {
    id: "11",
    name: "Ashwagandha Juice",
    slug: "ashwagandha-juice",
    price: 349,
    image: "/certifiedIcons/product.jpeg",
    category: "featured",
    rating: 5,
  },
  {
    id: "12",
    name: "Tulsi Tablets",
    slug: "tulsi-tablets",
    price: 199,
    image: "/certifiedIcons/product.jpeg",
    category: "featured",
    rating: 4,
  },
  {
    id: "13",
    name: "Triphala Powder",
    slug: "triphala-powder",
    price: 249,
    image: "/certifiedIcons/product.jpeg",
    category: "featured",
    rating: 5,
  },
  // 👇 Naye Combo Products Yahan Add Kiye Gaye Hain 👇
  {
    id: "14",
    name: "Herbal Wellness Pack",
    slug: "herbal-wellness-pack",
    price: 799,
    image: "/certifiedIcons/product.jpeg",
    category: "combo",
  },
  {
    id: "15",
    name: "Detox & Immunity Kit",
    slug: "detox-immunity-kit",
    price: 1199,
    image: "/certifiedIcons/product.jpeg",
    category: "combo",
  },
  {
    id: "16",
    name: "Organic Tea Combo",
    slug: "organic-tea-combo",
    price: 499,
    image: "/certifiedIcons/product.jpeg",
    category: "combo",
  },
];